### ISSUE TITLE
Add Quoted Triples and Annotation syntax from CG report

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-turtle#26]
This can wait for semantics decisions before adding Annotation syntax, but we should probably get quoted triples in to align with N-Triples/N-Quads.

**Comment by domel** [comment]
Agree, especially since sparql-query already has such PR.

**Comment by afs** [comment]
We can use the SPARQL grammar as a single place to agree on rule naming and rule order then replicate that for consistency.

I agree that annotation syntax is "unclear" - both UCR and semantics will have input.

Annotation syntax is in https://github.com/w3c/sparql-query/pull/78 without any opinion attached. It is a bit easier to do all once, now then remove later than it is to two design steps when the second step may uncover issues with the first.

Online validator: https://www.sparql.org/query-validator.html 

Jena does have an internal Turtle parser based on a generated grammar that can be updated to aligned to the query PR, if that helps.
