### ISSUE TITLE
Turtle 1.2 - question

### ISSUE THREAD

**Issue by ontoconsult** [w3c/rdf-turtle#40]
In Turtle 1.2 I need to be able to type a predicate.
Example: 
X isConnectedTo Y, where:
isConnectedTo rdf:type http://data.15926.org/rdl/RDS2229203 .

Also I need to be able to link meta data to that predicate.

Please let me know.

**Comment by TallTed** [comment]
Where is the problem you see?

Your predicate needs to be identified by a URI, as with all predicates.

And any predicate so identified can be described in RDF, just like any ontology may be so described, a la --
```turtle
PREFIX  example:  <http://example.com/myontology/>
PREFIX  rdl:      <http://data.15926.org/rdl/>

example:isConnectedTo
   rdf:type             rdl:RDS2229203                             ;
   rdfs:domain          example:FlangedArtefact                    ;
   rdfs:range           example:FlangedArtefact                    ;
   schema:dateCreated   "2023-09-06T13:20:00-05:00"^^xsd:dateTime  ;
   schema:dateModified  "2023-09-06T13:21:00-05:00"^^xsd:dateTime  .
```

Have I missed anything?

**Comment by ontoconsult** [comment]
Hi Ted,

 

Interesting to see the similarity with the following ISO 15926 Template instance:

 

ex:b42d081c-24ae-4d22-a908-6ef211d913f9

      rdf:type tpl:ClassifiedDirectConnectionOfTwoIndividuals <https://15926.blog/templates/IN-STRUC-540.xml>  ;

      tpl:hasSide1 ex:a1d691f2-06cc-45d9-a579-201f6f614e70 ;  # Line RZ17801-OUT (declared as such)

      tpl:hasSide2 ex:9906c494-f186-43c8-bde8-5f24b050c468 ;  # Pump P-101-IN (declared as such)

      tpl:hasDirectConnectionType rdl:RDS2229203 <http://data.15926.org/rdl/RDS2229203>  ; # FLANGED CONNECTION (declared as such in Reference Data Library)

      tpl:hasDirectConnection ex:55c7c816-9df6-46b9-b41d-2d5938893ef7 ; # auto-generated, in this case used in a template defining material, such as a gasket <http://data.15926.org/rdl/RDS1025774> 

      meta:valEffectiveDate "2022-03-01T17:15:00Z"^^xsd:dateTime .

 

Keep in mind that all predicates are a representation of information in which two declared things play a given role. 

I expect predicates in RDF 1.2 to get their own identity (UUID) that can also be used in the role of subject and object (RDF needs an extra inverse property).

 

The problem with your solution is that there are thousands of flanged connections in a process plant.

Your example:isConnectedTo defines the semantics (or rather: the syntax) of a flanged connection in general, but can’t be used for individual connections that are made at different dateTimes and unmade at other dateTimes by a particular construction person. 

 

So, your example should, imho, be rephrased as follows:

 

ex:isConnectedTo
   rdf:type             rdf:predicate ;
   rdfs:domain          ex:Thing ; # i.e. anything can be connected to something
   rdfs:range           ex:Thing ;
   schema:dateCreated   "2023-09-06T13:20:00-05:00"^^xsd:dateTime  ;
   schema:dateModified  "2023-09-06T13:21:00-05:00"^^xsd:dateTime  .
 
Then:
 

ex:a1d691f2-06cc-45d9-a579-201f6f614e70   ex:3f4f7ae6-ad0b-423d-bd42-9706fcb85a1b   ex:9906c494-f186-43c8-bde8-5f24b050c468 .

ex:3f4f7ae6-ad0b-423d-bd42-9706fcb85a1b   rdf:type  ex:isConnectedTo .

ex:3f4f7ae6-ad0b-423d-bd42-9706fcb85a1b   rdf:type  rdl:RDS2229203 <http://data.15926.org/rdl/RDS2229203>  . # FLANGED CONNECTION

ex:3f4f7ae6-ad0b-423d-bd42-9706fcb85a1b   ex: 87215de2-844f-4441-a7b7-e1af88bfabee  ex:e0de9f62-d5be-419f-8091-80bd176824c8 . # John Doe

ex: 87215de2-844f-4441-a7b7-e1af88bfabee  rdf:type  ex:isInstalledBy .     

etc

 

But I am afraid that neither the RDF, nor the OWL community will accept this. Too straightforward.

 

Please correct me when and where I went overboard.

 

Regards, Hans 

____________________________________________

**Comment by TallTed** [comment]
@ontoconsult --

Unfortunately, Markdown formatting doesn't work on email comments to GitHub, but a fair bit of your comment really needs formatting to be read properly. I encourage you to delete (or edit to nearly nothing) [your comment above](https://github.com/w3c/rdf-turtle/issues/40#issuecomment-1710180469), and resubmit it through the GitHub web interface. When you do that, I strongly encourage you to use whitespace to align the columns of your Turtle, as this helps human comprehension enormously.

> But I am afraid that neither the RDF, nor the OWL community will accept this. Too straightforward.

Being a member of both of those communities, I'm somewhat offended by your characterization. While OWL *can* be convoluted, depending on what you're trying to do, RDF is one of, if not the most straightforward languages I've worked with anywhere. Virtually anything can be described in a set of triples, which can be made into quads via named graphs or other context declarations to address things like change over time or different data reporters, and the world's your oyster.

Now, it's important to recognize that RDF (directed graph data) is not the best tool for every job. It's VERY well suited for sparse data, and for scenarios where you start off not knowing all the properties/predicates that will be relevant to your project. SQL (tabular data) is often a better choice for dense data, and for scenarios where you start off knowing exactly what columns (a/k/a properties or predicates) will be relevant to your project. Being able to use both and combine them as appropriate in a given project can be downright magical, and that's what my employer (OpenLink Software) has delivered in Virtuoso for well over a decade.

All that said — only knowing what you've stated above (and probably not fully understanding your examples), it appears to me that you may be better off (at least partially) in the SQL tabular relational world than in the RDF directed graph relational world. But that's only a hunch, at this point. I'd need to know much more about your project to be able to say this with certainty.

**Comment by pfps** [comment]
Is there anything that the working group should do here?  I'm tentatively marking this to be closed.   If anyone disagrees, just add a comment to the issue.
