### ISSUE TITLE
Escape character text

### ISSUE THREAD

**Issue by afs** [w3c/rdf-turtle#5]
The doc says:

"""
Literals delimited by ' (U+0027), may not contain the characters ', LF (U+000A), or CR (U+000D).
Literals delimited by ", may not contain the characters ", LF, or CR.
Literals delimited by ''' may not contain the sequence of characters '''.
Literals delimited by """ may not contain the sequence of characters """.
"""

It should say

"""
Literals delimited by ' (U+0027), may not contain an unescaped ' character, ... 
"""

or

"""
Literals delimited by ' (U+0027) must use an escape sequence to include the ' character,
"""

Similarly for "-strings and for triple quoted strings (`\'''` is possible).

**Comment by gkellogg** [comment]
Presumably keeping the restriction on `LF` and `CR` in each.

**Comment by afs** [comment]
Yes - it's the `...` above.

**Comment by gkellogg** [comment]
This was addressed in https://github.com/w3c/rdf-turtle/commit/4024306806575ea9b6116053e787eeafebde160d and can probably be closed.
