### ISSUE TITLE
Support multiple annotations on the same triple.

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-turtle#57]
Now that annotations introduce an intermediate reifier node,
it would make sense to allow multiple annotation "blocks" on a given asserted triple. E.g.

```turtle
:liz :spouse :richard {| :w1 | :in 1964 |}
                      {| :w2 | :in 1975 |}.
```

**Comment by niklasl** [comment]
Since support for this has landed, I think this issue can be closed? (As a feature, it's independent of any further syntax issues.)

For reference, the first example is now:
```
:liz :spouse :richard ~ :w1 {| :in 1964 |}
                      ~ :w2 {| :in 1975 |}.
```
