### ISSUE TITLE
Minor editorial issues

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-turtle#73]
(I put them all in one issue...)

[§2.7 Nesting of Blank Nodes without Blank Node Identifiers](https://www.w3.org/TR/rdf12-turtle/#unlabeled-bnodes), first paragraph, the second occurrence of blankNodePropertyList should be typeset as `<code>`

---
[§6.4 Escape Sequences](https://www.w3.org/TR/rdf12-turtle/#sec-escapes) third escape sequence row, the first "hex" (after `\U`) is an active link to the production rule, although the relevant row is reproduced underneath. It should probably look like the other occurrences of "hex".

---
[§6.6 Selected Terminal Literal Strings](https://www.w3.org/TR/rdf12-turtle/#selected-terminal-literal-strings), towards the end of the table of U+007E: shouldn't "tilda" be "tilde"? In Webster, ["tilde"](https://www.merriam-webster.com/dictionary/tilde) is a valid term; "tilda" does not exist in it. 

Also: U+007C: shouldn't it say "Vertical bar"? Note that the term "verticle" also appears in the list of literal sequences for `{|` and `|}`.

---

[§7.3.1 Reifiers](https://www.w3.org/TR/rdf12-turtle/#reifier) the word "the" is duplicated in the second sentence.

**Comment by TallTed** [comment]
"tilda" is definitely an error. The `~` character is a "tilde".

All occurrences of "verticle" are also certainly errors. At the same time, the [official name for U+007C](https://www.compart.com/en/unicode/U+007C) is "vertical line", which we should probably use instead of "vertical bar".
