### ISSUE TITLE
More about directions

### ISSUE THREAD

**Issue by iherman** [w3c/rdf-turtle#75]
In [§2.5.1 Quoted Literals](https://www.w3.org/TR/rdf12-turtle/#turtle-literals) as part of the examples, it may be better to use a "real" example for directions (the ones listed among the examples are really superfluous). E.g.,

```turtle
show:218 show:blurb "HTML و CSS: تصميم و إنشاء مواقع الويب"@ar--rtl.
```

or:

```turtle
show:218 show:blurb "HTML היא שפת סימון."@he--rtl
```

Maybe it is also important add a note whereby the text the value field in turtle represents the text as it is stored in memory and not as it is supposed to be displayed. (We spent quite some time to get it right in the spec for the [publication manifest](https://www.w3.org/TR/pub-manifest/#value-localizable-string), feel free to copy and paste.)

(In my experience, getting the spec examples right bidirectional text is a challenge; you should probably ask the i18n guys to check it.)

**Comment by afs** [comment]
(fixed syntax of `@ar--ltr`)

**Comment by gkellogg** [comment]
Note that RDF Concepts has a more general discussion of BIDI similar to what you pointed to in the ePub spec, which has been reviewed by the I18N group. But, we can add further explaination of `ltr` and `rtl` similar to what you have.

**Comment by pfps** [comment]
Wouldn't it also be useful to have an example where initial direction alone is insufficient?  I think that the examples involve a RTL language with embedded LTR strings that are separated by neutral characters.

**Comment by gkellogg** [comment]
Concepts expands more on this, but it could use a langString example which dominates directionality based on the first character.

**Comment by gkellogg** [comment]
Dear I18N people, I want to be sure that the recently added example for natively displaying Arabic RTL seems appropriate and correct.

**Comment by gkellogg** [comment]
> Wouldn't it also be useful to have an example where initial direction alone is insufficient? I think that the examples involve a RTL language with embedded LTR strings that are separated by neutral characters.

@pfps, see w3c/rdf-concepts#109, Specifically https://github.com/w3c/rdf-concepts/blob/0957e914d33cb39326aa6828d84b47fb0056530d/spec/index.html#L860-L864,

       <p>In the absence of an explicit initial text direction, the [[?UAX9]] algorithm
         can detect text direction from the initial character.
         For example "<bdi lang="ar">اَلأَعْشَى</bdi> - 1st place" displays the
         Arabic characters in a right-to-left fashion, while in memory
         they would be stored as "<bdo dir="ltr" lang="ar">اَلأَعْشَى</bdo> - 1st place"</p>
